DATASET:
  DATA_ROOT: /public/datasets/path/data/h5
  DATA_SET: PaviaU
  CATEGORY_NUM: 9
  CROP_SIZE: 32 #340
  MULTI_SCALE: False
  MCROP_SIZE: [16, 32, 48]
  OVERLAP: True
  TRAIN_NUM: 20
  VAL_NUM: 10
SEARCH:
  TIE_CELL: False
DATALOADER:
  BATCH_SIZE_TEST: 10
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: HSI_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 3
  PRIMITIVES_SPE: "HSI_SPE"
  PRIMITIVES_SPA: "HSI_SPA"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True

OUTPUT_DIR: /public/datasets/path/model/

