DATASET:
  DATA_ROOT: /data/data2/path/data/HSIs/h5
  DATA_SET: HoustonU
  CATEGORY_NUM: 15
  CROP_SIZE: 14
  PATCHES_NUM: 400
  TRAIN_NUM: 30
  VAL_NUM: 10
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 30
  TIE_CELL: False

MODEL:
  META_ARCHITECTURE: HSI_supernet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 3
  FILTER_MULTIPLIER: 8
  PRIMITIVES_SPE: "HSI_SPE"
  PRIMITIVES_SPA: "HSI_SPA"
  ACTIVATION_F: "Leaky"
  AFFINE: False
  USE_ASPP: True
DATALOADER:
  BATCH_SIZE_TRAIN: 5
  BATCH_SIZE_TEST: 5
  NUM_WORKERS: 2
  DATA_LIST_DIR: ../preprocess/dataset_db

SOLVER:
  MAX_EPOCH: 150
  CHECKPOINT_PERIOD: 1

OUTPUT_DIR:  /data/data2/path/hsi_model/