DATASET:
  DATA_ROOT:  /public/datasets/path/data/h5
  DATA_SET: Pavia
  CATEGORY_NUM: 9
  CROP_SIZE: 24
  PATCHES_NUM: 400
  TRAIN_NUM: 20
  VAL_NUM: 10
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 16
  TIE_CELL: False
MODEL:
  META_ARCHITECTURE: HSI_supernet
  META_MODE: Width
  NUM_LAYERS: 4
  NUM_BLOCKS: 3
  FILTER_MULTIPLIER: 8
  PRIMITIVES_SPE: "HSI_SPE"
  PRIMITIVES_SPA: "HSI_SPA"
  ACTIVATION_F: "Leaky"
  AFFINE: False
  USE_ASPP: True
DATALOADER:
  BATCH_SIZE_TRAIN: 6
  BATCH_SIZE_TEST: 6
  NUM_WORKERS: 0
  DATA_LIST_DIR: ../preprocess/dataset_db

SOLVER:
  MAX_EPOCH: 100
  CHECKPOINT_PERIOD: 1

OUTPUT_DIR: /public/datasets/path/model/