DATASET:
  DATA_ROOT: /public/datasets/path/data/h5
  DATA_SET: Pavia
  CATEGORY_NUM: 9
  CROP_SIZE: 32
  PATCHES_NUM: 4000
  NBAND: 102
  TRAIN_NUM: 30
  VAL_NUM: 10
SEARCH:
  TIE_CELL: False
SOLVER:
  TRAIN:
    MAX_ITER: 600000
  CHECKPOINT_PERIOD: 500
  VALIDATE_PERIOD: 500
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE_TRAIN: 12
  BATCH_SIZE_TEST: 12
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: HSI_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 4
  NUM_BLOCKS: 3
  PRIMITIVES_SPE: "HSI_SPE"
  PRIMITIVES_SPA: "HSI_SPA"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True

OUTPUT_DIR: /public/datasets/path/model/

